# Generated by Django 4.2.1 on 2023-05-26 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='choices',
            new_name='verify_type',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heif', 'jpeg', 'heic'])]),
        ),
    ]
