# Generated by Django 4.2.2 on 2023-06-08 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_choices_userconfirmation_verify_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heif', 'jpeg', 'heic'])]),
        ),
    ]
